FROM postgres:14.19-alpine3.21
# docker run --name postgres-demo -d -v /home/data:/data/ps postgres - делаем первый bind mount
# docker run --name postgres-demo-2 -d -v /home/data-2:/data/ps postgres - запускаем второй контейнер и делаем еще однин bind mount на другую директорию